### ISSUE TITLE
OpenSUSE tumbleweed install presubmit is failing

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/cpp-cmakefiles#10]
Example:
https://source.cloud.google.com/results/invocations/96360c94-99fd-4277-a1fe-1c8db9e21874/targets

```
Problem: pkgconf-pkg-config-1.6.1-2.1.x86_64 conflicts with pkg-config < 0.29.2+1 provided by pkg-config-0.29.2-3.5.x86_64
 Solution 1: Following actions will be done:
  deinstallation of pkgconf-pkg-config-1.6.1-2.1.x86_64
  deinstallation of pkgconf-m4-1.6.1-2.1.noarch
 Solution 2: do not install pkg-config-0.29.2-3.5.x86_64
```

**Comment by coryan** [comment]
It is possible that the openSUSE package database is not in good shape today, sometimes adding a `--allow-downgrade` fixes these problems.

**Comment by tmatsuo** [comment]
Good to know, thanks. However in this case, just not installing pkg-config seems to still work (this means you don't need to install pkg-config), so I'll go that path.

**Comment by coryan** [comment]
SGTM.
