### ISSUE TITLE
Add cloudtrace/v2 to project output

### ISSUE THREAD

**Issue by curtpm** [googleapis/cpp-cmakefiles#15]
none of the protobuf files for cloudtrace/v2 are currently compiled or exported by this project. 

Im looking at using this project:
https://github.com/census-instrumentation/opencensus-cpp/blob/master/opencensus/exporters/trace/stackdriver/stackdriver_exporter.h

**Comment by coryan** [comment]
We can probably schedule this work.  But my guess is you also need the work described in census-instrumentation/opencensus-cpp#244
