### ISSUE TITLE
Define build matrix for this project

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/cpp-cmakefiles#3]
@coryan FYI

We're adding kokoro ci builds with #1. Now we're testing Ubuntu 16.04, Ubuntu 18.04, Cent OS 7, and Fedora 30, but we have more to cover. Once we define the build matrix, we'll create issues for it.

Excerpt from https://github.com/googleapis/cpp-cmakefiles/pull/1#discussion_r302049527

> We certainly want to test gcc-4.8, clang-3.8, ubuntu-18.04 (but also 16.04), we also want to
> test the latest and greatest GCC and Clang, we want to test other distros, and macOS, and 
> Windows.
> We want to test producing shared libraries and static libraries too.

**Comment by devjgm** [comment]
We're moving this project the https://github.com/googleapis/google-cloud-cpp/ monorepo, so this issue will be obsolete at that point since the matrix of builds in that repo will be used.
